site :opscode

cookbook 'build-essential', '~> 2.0.4'
cookbook 'nginx', '~> 2.7.4'
cookbook 'sudo', '~> 2.7.0'
cookbook 'chef-solo-search', '~> 0.5.1'
cookbook 'users', '~> 1.7.0'
cookbook 'mysql', '~> 5.3.6'
cookbook 'php', '~> 1.4.6'
cookbook 'php-fpm', '~> 0.6.10'
cookbook 'git', '~> 4.0.2'
cookbook 'php5-fpm', '~> 0.2.0'
cookbook 'composer', '~> 1.0.3'
